/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iai_pri_PRIJNI */

#ifndef _Included_com_iai_pri_PRIJNI
#define _Included_com_iai_pri_PRIJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    imageToGround
 * Signature: (J[Lcom/iai/pri/PRIImagePoint;)[Lcom/iai/pri/PRIGroundPoint;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iai_pri_PRIJNI_imageToGround
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    groundToImage
 * Signature: (J[Lcom/iai/pri/PRIGroundPoint;)[Lcom/iai/pri/PRIImagePoint;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iai_pri_PRIJNI_groundToImage
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getHeightOffsetTopToShadowTip
 * Signature: (JLcom/iai/pri/PRIImagePoint;Lcom/iai/pri/PRIImagePoint;)Lcom/iai/pri/PRIGroundPoint;
 */
JNIEXPORT jobject JNICALL Java_com_iai_pri_PRIJNI_getHeightOffsetTopToShadowTip__JLcom_iai_pri_PRIImagePoint_2Lcom_iai_pri_PRIImagePoint_2
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getHeightOffsetTopToShadowTip
 * Signature: (JLcom/iai/pri/PRIImagePoint;JLcom/iai/pri/PRIImagePoint;)Lcom/iai/pri/PRIGroundPoint;
 */
JNIEXPORT jobject JNICALL Java_com_iai_pri_PRIJNI_getHeightOffsetTopToShadowTip__JLcom_iai_pri_PRIImagePoint_2JLcom_iai_pri_PRIImagePoint_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getHeightOffsetBaseToShadowTip
 * Signature: (JLcom/iai/pri/PRIImagePoint;Lcom/iai/pri/PRIImagePoint;)D
 */
JNIEXPORT jdouble JNICALL Java_com_iai_pri_PRIJNI_getHeightOffsetBaseToShadowTip__JLcom_iai_pri_PRIImagePoint_2Lcom_iai_pri_PRIImagePoint_2
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getHeightOffsetBaseToShadowTip
 * Signature: (JLcom/iai/pri/PRIImagePoint;JLcom/iai/pri/PRIImagePoint;)D
 */
JNIEXPORT jdouble JNICALL Java_com_iai_pri_PRIJNI_getHeightOffsetBaseToShadowTip__JLcom_iai_pri_PRIImagePoint_2JLcom_iai_pri_PRIImagePoint_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getHeightOffsetBaseToTop
 * Signature: (JLcom/iai/pri/PRIImagePoint;Lcom/iai/pri/PRIImagePoint;)D
 */
JNIEXPORT jdouble JNICALL Java_com_iai_pri_PRIJNI_getHeightOffsetBaseToTop__JLcom_iai_pri_PRIImagePoint_2Lcom_iai_pri_PRIImagePoint_2
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getHeightOffsetBaseToTop
 * Signature: (JLcom/iai/pri/PRIImagePoint;JLcom/iai/pri/PRIImagePoint;)D
 */
JNIEXPORT jdouble JNICALL Java_com_iai_pri_PRIJNI_getHeightOffsetBaseToTop__JLcom_iai_pri_PRIImagePoint_2JLcom_iai_pri_PRIImagePoint_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    isPRI
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iai_pri_PRIJNI_isPRI__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    isPRI
 * Signature: (Ljava/io/InputStream;)J
 */
JNIEXPORT jlong JNICALL Java_com_iai_pri_PRIJNI_isPRI__Ljava_io_InputStream_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getCorners
 * Signature: (J)Lcom/iai/pri/PRICorners;
 */
JNIEXPORT jobject JNICALL Java_com_iai_pri_PRIJNI_getCorners
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getElevation
 * Signature: (JDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_iai_pri_PRIJNI_getElevation
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getNumElevationSegments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_iai_pri_PRIJNI_getNumElevationSegments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    getElevationSegmentData
 * Signature: (JI)Lcom/iai/pri/ElevationSegmentData;
 */
JNIEXPORT jobject JNICALL Java_com_iai_pri_PRIJNI_getElevationSegmentData
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    loadImage
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_iai_pri_PRIJNI_loadImage__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    loadImage
 * Signature: (Ljava/io/InputStream;)J
 */
JNIEXPORT jlong JNICALL Java_com_iai_pri_PRIJNI_loadImage__Ljava_io_InputStream_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_iai_pri_PRIJNI
 * Method:    clearImageCache
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_iai_pri_PRIJNI_clearImageCache
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
