msxsl "..\xsd\details\__chat.xsd" xs3p.xsl -v -o "..\html\details\__chat.html"
msxsl "..\xsd\details\__geofence.xsd" xs3p.xsl -v -o "..\html\details\__geofence.html"
msxsl "..\xsd\details\__group.xsd" xs3p.xsl -v -o "..\html\details\__group.html"
msxsl "..\xsd\details\__serverdestination.xsd" xs3p.xsl -v -o "..\html\details\__serverdestination.html"
msxsl "..\xsd\details\__video.xsd" xs3p.xsl -v -o "..\html\details\__video.html"
msxsl "..\xsd\details\archive.xsd" xs3p.xsl -v -o "..\html\details\archive.html"
msxsl "..\xsd\details\attachment_list.xsd" xs3p.xsl -v -o "..\html\details\attachment_list.html"
msxsl "..\xsd\details\color.xsd" xs3p.xsl -v -o "..\html\details\color.html"
msxsl "..\xsd\details\contact.xsd" xs3p.xsl -v -o "..\html\details\contact.html"
msxsl "..\xsd\details\emergency.xsd" xs3p.xsl -v -o "..\html\details\emergency.html"
msxsl "..\xsd\details\environment.xsd" xs3p.xsl -v -o "..\html\details\environment.html"
msxsl "..\xsd\details\fileshare.xsd" xs3p.xsl -v -o "..\html\details\fileshare.html"
msxsl "..\xsd\details\fillColor.xsd" xs3p.xsl -v -o "..\html\details\fillColor.html"
msxsl "..\xsd\details\height.xsd" xs3p.xsl -v -o "..\html\details\height.html"
msxsl "..\xsd\details\height_unit.xsd" xs3p.xsl -v -o "..\html\details\height_unit.html"
msxsl "..\xsd\details\labels_on.xsd" xs3p.xsl -v -o "..\html\details\labels_on.html"
msxsl "..\xsd\details\link.xsd" xs3p.xsl -v -o "..\html\details\link.html"
msxsl "..\xsd\details\mission.xsd" xs3p.xsl -v -o "..\html\details\mission.html"
msxsl "..\xsd\details\precisionlocation.xsd" xs3p.xsl -v -o "..\html\details\precisionlocation.html"
msxsl "..\xsd\details\remarks.xsd" xs3p.xsl -v -o "..\html\details\remarks.html"
msxsl "..\xsd\details\shape.xsd" xs3p.xsl -v -o "..\html\details\shape.html"
msxsl "..\xsd\details\status.xsd" xs3p.xsl -v -o "..\html\details\status.html"
msxsl "..\xsd\details\strokeColor.xsd" xs3p.xsl -v -o "..\html\details\strokeColor.html"
msxsl "..\xsd\details\strokeWeight.xsd" xs3p.xsl -v -o "..\html\details\strokeWeight.html"
msxsl "..\xsd\details\takv.xsd" xs3p.xsl -v -o "..\html\details\takv.html"
msxsl "..\xsd\details\track.xsd" xs3p.xsl -v -o "..\html\details\track.html"
msxsl "..\xsd\details\uid.xsd" xs3p.xsl -v -o "..\html\details\uid.html"
msxsl "..\xsd\details\usericon.xsd" xs3p.xsl -v -o "..\html\details\usericon.html"

msxsl "..\xsd\event\point.xsd" xs3p.xsl -v -o "..\html\event\point.html"

msxsl "..\xsd\Drawing Shapes - Circle.xsd" xs3p.xsl -v -o "..\html\Drawing Shapes - Circle.html"
msxsl "..\xsd\Drawing Shapes - Free Form.xsd" xs3p.xsl -v -o "..\html\Drawing Shapes - Free Form.html"
msxsl "..\xsd\Drawing Shapes - Rectangle.xsd" xs3p.xsl -v -o "..\html\Drawing Shapes - Rectangle.html"
msxsl "..\xsd\Drawing Shapes - Telestration.xsd" xs3p.xsl -v -o "..\html\Drawing Shapes - Telestration.html"
msxsl "..\xsd\Geo Fence.xsd" xs3p.xsl -v -o "..\html\Geo Fence.html"
msxsl "..\xsd\Marker - 2525.xsd" xs3p.xsl -v -o "..\html\Marker - 2525.html"
msxsl "..\xsd\Marker - Icon Set.xsd" xs3p.xsl -v -o "..\html\Marker - Icon Set.html"
msxsl "..\xsd\Marker - Spot.xsd" xs3p.xsl -v -o "..\html\Marker - Spot.html"
msxsl "..\xsd\Range & Bearing - Bullseye.xsd" xs3p.xsl -v -o "..\html\Range & Bearing - Bullseye.html"
msxsl "..\xsd\Range & Bearing - Circle.xsd" xs3p.xsl -v -o "..\html\Range & Bearing - Circle.html"
msxsl "..\xsd\Range & Bearing - Line.xsd" xs3p.xsl -v -o "..\html\Range & Bearing - Line.html"
msxsl "..\xsd\Route.xsd" xs3p.xsl -v -o "..\html\Route.html"
